apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:sachinratan/helm-charts
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: srshinde/jdk-mvn-app
      tag: 2021-09-04T10-21-e09bc03-142
    replicaCount: 1
    hpa:
      enabled: false
