---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:sachinratan/helm-charts
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: srshinde/podinfo
      tag: stg-rd6diy4m
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 4
      cpu: 50
      memory: 256Mi
